module.exports.typeIds = {
  amusement_park: 1,
  aquarium: 2,
  art_gallery: 3,
  bowling_alley: 4,
  book_store: 5,
  casino: 6,
  clothing_store: 7,
  point_of_interest: 8,
  shopping_mall: 9,
  library: 10,
  movie_theater: 11,
  museum: 12,
  night_club: 13,
  park: 14,
  stadium: 15,
  zoo: 16,
};

module.exports.typePlurals = {
  amusement_park: 'Amusement parks',
  aquarium: 'Aquariums',
  art_gallery: 'Art galleries',
  bowling_alley: 'Bowling alleys',
  book_store: 'Book stores',
  casino: 'Casinos',
  clothing_store: 'Clothing stores',
  point_of_interest: 'Points of interest',
  shopping_mall: 'Shopping malls',
  library: 'Libraries',
  movie_theater: 'Movie theaters',
  museum: 'Museums',
  night_club: 'Night clubs',
  park: 'Parks',
  stadium: 'Stadiums',
  zoo: 'Zoos',
};
